name: vgv_weather_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0-nullsafety.3
  flutter_bloc: ^7.0.0-nullsafety.4
  intl: ^0.17.0
  http: ^0.13.0
  equatable: ^2.0.0
  simple_animations: ^3.0.1 
  vgv_core:
    path: lib/core
  vgv_weather_city:
    path: lib/features/city
  vgv_weather_temperature_switch:
    path: lib/features/temperature_switch
  vgv_theme:
    path: lib/features/theme

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0-nullsafety.1
  mocktail: 0.0.1-dev.12
  very_good_analysis: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
